### ISSUE TITLE
No Validations on Setup Page

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#3]
<img width="1410" alt="Screenshot 2021-07-14 at 4 31 11 PM" src="https://user-images.githubusercontent.com/56086942/125611636-1b1816a1-7c12-4763-8d57-7fe2d9085153.png">

No validations on this page, If you enter incorrect email, phone number, domain it all accepts it. Rather there should be a validation if the inputed format for any of the fields is incorrect, it should stop the user there itself asking to enter the correct data and then allow them to proceed to next screen if the data entered is as per format. Please see the attached screenshot.

**Comment by NathanLeadill** [comment]
Fixed, going out in 0.823

**Comment by jubisha** [comment]
Still not working
USer name - yiser27090@eyeremind.com
Paswd - 123
register with the above email, do not enter data in any of the fields on set up page, hit next, it proceeds, rather it should stop u there asking to input the data

also,if the data entered in any of the fields is incorrect like in email if i enter "Ds" it accepts, it should throw proper validation to say that the format is incorrect pls enter valid data.

I have cleared the cache and tested

**Comment by NathanLeadill** [comment]
Fixed
