### ISSUE TITLE
No Validations on the whitelabel page

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#4]
Again no validations on the whitelabel page

<img width="1268" alt="Screenshot 2021-07-14 at 4 35 57 PM" src="https://user-images.githubusercontent.com/56086942/125612194-86359177-3671-420c-bf9a-449e92ebbac2.png">

**Comment by NathanLeadill** [comment]
Fixed, going out in 0.823

**Comment by jubisha** [comment]
Still not working
USer name - yiser27090@eyeremind.com
Paswd - 123

**Comment by NathanLeadill** [comment]
Fix going out now
